services:
  SpeedTest_Exporter:
      image: ${IMAGE_NAME}
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: ${CONTAINER_NAME}
      hostname: ${HOSTNAME}
      restart: unless-stopped
      environment:
        TZ: ${SYSTEM_TIME_ZONE}
        API_PORT: ${EXTERNAL_PORT}
        INTERFACE_IP: ${IP}
      ports:
        - ${EXTERNAL_PORT}:8000
      healthcheck:
        test: curl --fail http://${HOSTNAME}:8000/docs
        start_period: 30s
        interval: 1m
        timeout: 1s
        retries: 5