services:
  SpeedTest_Exporter:
      image: horna-home-lab/speedtest_exporter
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: ${CONTAINER_NAME}
      hostname: ${HOSTNAME}
      restart: unless-stopped
      environment:
        TZ: ${SYSTEM_TIME_ZONE}
        SPEED_TEST_INTERVAL_MINUTES: ${SPEED_TEST_INTERVAL_MINUTES}
        API_PORT: ${EXTERNAL_PORT}
        INTERFACE_IP: ${IP}
      ports:
        - ${EXTERNAL_PORT}:8000
      healthcheck:
        test: curl --fail http://${HOSTNAME}:8000/docs
        start_period: 2s
        interval: 3s
        timeout: 1s
        retries: 5